// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameActorEvent = "actor_events"

// ActorEvent mapped from table <actor_events>
type ActorEvent struct {
	Height     int64   `gorm:"column:height;type:bigint;primaryKey" json:"height"`
	StateRoot  string  `gorm:"column:state_root;type:text;primaryKey" json:"state_root"`
	EventIndex int64   `gorm:"column:event_index;type:bigint;primaryKey" json:"event_index"`
	MessageCid string  `gorm:"column:message_cid;type:text;primaryKey" json:"message_cid"`
	Emitter    string  `gorm:"column:emitter;type:text;not null" json:"emitter"`
	Flags      []uint8 `gorm:"column:flags;type:bytea;not null" json:"flags"`
	Key        string  `gorm:"column:key;type:text;not null" json:"key"`
	Value      []uint8 `gorm:"column:value;type:bytea;not null" json:"value"`
}

// TableName ActorEvent's table name
func (*ActorEvent) TableName() string {
	return TableNameActorEvent
}
