// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameActorState = "actor_states"

// ActorState mapped from table <actor_states>
type ActorState struct {
	Head   string `gorm:"column:head;type:text;primaryKey" json:"head"`       // CID of the root of the state tree for the actor.
	Code   string `gorm:"column:code;type:text;primaryKey" json:"code"`       // CID identifier for the type of the actor.
	State  string `gorm:"column:state;type:jsonb;not null" json:"state"`      // Top level of state data.
	Height int64  `gorm:"column:height;type:bigint;primaryKey" json:"height"` // Epoch when this state change happened.
}

// TableName ActorState's table name
func (*ActorState) TableName() string {
	return TableNameActorState
}
