// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBlockParent = "block_parents"

// BlockParent mapped from table <block_parents>
type BlockParent struct {
	Block  string `gorm:"column:block;type:text;primaryKey" json:"block"`     // CID of the block.
	Parent string `gorm:"column:parent;type:text;primaryKey" json:"parent"`   // CID of the parent block.
	Height int64  `gorm:"column:height;type:bigint;primaryKey" json:"height"` // Epoch when the block was mined.
}

// TableName BlockParent's table name
func (*BlockParent) TableName() string {
	return TableNameBlockParent
}
