// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBlockMessage = "block_messages"

// BlockMessage mapped from table <block_messages>
type BlockMessage struct {
	Block   string `gorm:"column:block;type:text;primaryKey" json:"block"`     // CID of the block that contains the message.
	Message string `gorm:"column:message;type:text;primaryKey" json:"message"` // CID of a message in the block.
	Height  int64  `gorm:"column:height;type:bigint;primaryKey" json:"height"` // Epoch when the block was mined.
}

// TableName BlockMessage's table name
func (*BlockMessage) TableName() string {
	return TableNameBlockMessage
}
