// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChainConsensu = "chain_consensus"

// ChainConsensu mapped from table <chain_consensus>
type ChainConsensu struct {
	Height          int64   `gorm:"column:height;type:bigint;primaryKey" json:"height"`
	ParentStateRoot string  `gorm:"column:parent_state_root;type:text;primaryKey" json:"parent_state_root"`
	ParentTipSet    string  `gorm:"column:parent_tip_set;type:text;primaryKey" json:"parent_tip_set"`
	TipSet          *string `gorm:"column:tip_set;type:text" json:"tip_set"`
}

// TableName ChainConsensu's table name
func (*ChainConsensu) TableName() string {
	return TableNameChainConsensu
}
