// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChainEconomic = "chain_economics"

// ChainEconomic mapped from table <chain_economics>
type ChainEconomic struct {
	Height              int64   `gorm:"column:height;type:bigint;primaryKey" json:"height"`                              // Epoch of the economic summary.
	ParentStateRoot     string  `gorm:"column:parent_state_root;type:text;primaryKey" json:"parent_state_root"`          // CID of the parent state root.
	CirculatingFil      float64 `gorm:"column:circulating_fil;type:numeric;not null" json:"circulating_fil"`             // The amount of FIL (attoFIL) circulating and tradeable in the economy. The basis for Market Cap calculations.
	VestedFil           float64 `gorm:"column:vested_fil;type:numeric;not null" json:"vested_fil"`                       // Total amount of FIL (attoFIL) that is vested from genesis allocation.
	MinedFil            float64 `gorm:"column:mined_fil;type:numeric;not null" json:"mined_fil"`                         // The amount of FIL (attoFIL) that has been mined by storage miners.
	BurntFil            float64 `gorm:"column:burnt_fil;type:numeric;not null" json:"burnt_fil"`                         // Total FIL (attoFIL) burned as part of penalties and on-chain computations.
	LockedFil           float64 `gorm:"column:locked_fil;type:numeric;not null" json:"locked_fil"`                       // The amount of FIL (attoFIL) locked as part of mining, deals, and other mechanisms.
	FilReserveDisbursed float64 `gorm:"column:fil_reserve_disbursed;type:numeric;not null" json:"fil_reserve_disbursed"` // The amount of FIL (attoFIL) that has been disbursed from the mining reserve.
}

// TableName ChainEconomic's table name
func (*ChainEconomic) TableName() string {
	return TableNameChainEconomic
}
