// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataCapBalance = "data_cap_balances"

// DataCapBalance mapped from table <data_cap_balances>
type DataCapBalance struct {
	Height    int64   `gorm:"column:height;type:bigint;primaryKey" json:"height"`                  // Epoch at which DataCap balances state changed.
	StateRoot string  `gorm:"column:state_root;type:text;primaryKey" json:"state_root"`            // CID of the parent state root at this epoch.
	Address   string  `gorm:"column:address;type:text;primaryKey" json:"address"`                  // Address of verified datacap client this state change applies to.
	DataCap   float64 `gorm:"column:data_cap;type:numeric;not null" json:"data_cap"`               // DataCap of verified datacap client at this state change.
	Event     string  `gorm:"column:event;type:data_cap_balance_event_type;not null" json:"event"` // Name of the event that occurred (ADDED, MODIFIED, REMOVED).
}

// TableName DataCapBalance's table name
func (*DataCapBalance) TableName() string {
	return TableNameDataCapBalance
}
