// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDrandBlockEntry = "drand_block_entries"

// DrandBlockEntry mapped from table <drand_block_entries>
type DrandBlockEntry struct {
	Round int64  `gorm:"column:round;type:bigint;not null" json:"round"` // The round number of the randomness used.
	Block string `gorm:"column:block;type:text;not null" json:"block"`   // CID of the block.
}

// TableName DrandBlockEntry's table name
func (*DrandBlockEntry) TableName() string {
	return TableNameDrandBlockEntry
}
