// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameIDAddress = "id_addresses"

// IDAddress mapped from table <id_addresses>
type IDAddress struct {
	Height    int64  `gorm:"column:height;type:bigint;primaryKey" json:"height"`       // Epoch at which this address mapping was added.
	ID        string `gorm:"column:id;type:text;primaryKey" json:"id"`                 // ID of the actor.
	Address   string `gorm:"column:address;type:text;primaryKey" json:"address"`       // Robust address of the actor.
	StateRoot string `gorm:"column:state_root;type:text;primaryKey" json:"state_root"` // CID of the parent state root at which this address mapping was added.
}

// TableName IDAddress's table name
func (*IDAddress) TableName() string {
	return TableNameIDAddress
}
