// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMarketDealState = "market_deal_states"

// MarketDealState mapped from table <market_deal_states>
type MarketDealState struct {
	DealID           int64  `gorm:"column:deal_id;type:bigint;primaryKey" json:"deal_id"`                     // Identifier for the deal.
	SectorStartEpoch int64  `gorm:"column:sector_start_epoch;type:bigint;not null" json:"sector_start_epoch"` // Epoch this deal was included in a proven sector. -1 if not yet included in proven sector.
	LastUpdateEpoch  int64  `gorm:"column:last_update_epoch;type:bigint;not null" json:"last_update_epoch"`   // Epoch this deal was last updated at. -1 if deal state never updated.
	SlashEpoch       int64  `gorm:"column:slash_epoch;type:bigint;not null" json:"slash_epoch"`               // Epoch this deal was slashed at. -1 if deal was never slashed.
	StateRoot        string `gorm:"column:state_root;type:text;primaryKey" json:"state_root"`                 // CID of the parent state root for this deal.
	Height           int64  `gorm:"column:height;type:bigint;primaryKey" json:"height"`                       // Epoch at which this deal was added or changed.
}

// TableName MarketDealState's table name
func (*MarketDealState) TableName() string {
	return TableNameMarketDealState
}
