// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	Cid        string  `gorm:"column:cid;type:text;primaryKey" json:"cid"`                  // CID of the message.
	From       string  `gorm:"column:from;type:text;not null" json:"from"`                  // Address of the actor that sent the message.
	To         string  `gorm:"column:to;type:text;not null" json:"to"`                      // Address of the actor that received the message.
	SizeBytes  int64   `gorm:"column:size_bytes;type:bigint;not null" json:"size_bytes"`    // Size of the serialized message in bytes.
	Nonce      int64   `gorm:"column:nonce;type:bigint;not null" json:"nonce"`              // The message nonce, which protects against duplicate messages and multiple messages with the same values.
	Value      float64 `gorm:"column:value;type:numeric;not null" json:"value"`             // Amount of FIL (in attoFIL) transferred by this message.
	GasFeeCap  float64 `gorm:"column:gas_fee_cap;type:numeric;not null" json:"gas_fee_cap"` // The maximum price that the message sender is willing to pay per unit of gas.
	GasPremium float64 `gorm:"column:gas_premium;type:numeric;not null" json:"gas_premium"` // The price per unit of gas (measured in attoFIL/gas) that the message sender is willing to pay (on top of the BaseFee) to "tip" the miner that will include this message in a block.
	GasLimit   int64   `gorm:"column:gas_limit;type:bigint;not null" json:"gas_limit"`
	Method     *int64  `gorm:"column:method;type:bigint" json:"method"`            // The method number invoked on the recipient actor. Only unique to the actor the method is being invoked on. A method number of 0 is a plain token transfer - no method exectution.
	Height     int64   `gorm:"column:height;type:bigint;primaryKey" json:"height"` // Epoch this message was executed at.
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
