// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMessageParam = "message_params"

// MessageParam mapped from table <message_params>
type MessageParam struct {
	Cid    string   `gorm:"column:cid;type:text;primaryKey" json:"cid"` // The CID of a message.
	Params *[]uint8 `gorm:"column:params;type:bytea" json:"params"`     // The parameters of the message as bytes.
}

// TableName MessageParam's table name
func (*MessageParam) TableName() string {
	return TableNameMessageParam
}
