// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMinerSectorPost = "miner_sector_posts"

// MinerSectorPost mapped from table <miner_sector_posts>
type MinerSectorPost struct {
	MinerID        string  `gorm:"column:miner_id;type:text;primaryKey" json:"miner_id"`      // Address of the miner who owns the sector.
	SectorID       int64   `gorm:"column:sector_id;type:bigint;primaryKey" json:"sector_id"`  // Numeric identifier of the sector.
	Height         int64   `gorm:"column:height;type:bigint;primaryKey" json:"height"`        // Epoch at which this PoSt message was executed.
	PostMessageCid *string `gorm:"column:post_message_cid;type:text" json:"post_message_cid"` // CID of the PoSt message.
}

// TableName MinerSectorPost's table name
func (*MinerSectorPost) TableName() string {
	return TableNameMinerSectorPost
}
