// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMinerSectorEvent = "miner_sector_events"

// MinerSectorEvent mapped from table <miner_sector_events>
type MinerSectorEvent struct {
	MinerID   string `gorm:"column:miner_id;type:text;primaryKey" json:"miner_id"`              // Address of the miner who owns the sector.
	SectorID  int64  `gorm:"column:sector_id;type:bigint;primaryKey" json:"sector_id"`          // Numeric identifier of the sector.
	StateRoot string `gorm:"column:state_root;type:text;primaryKey" json:"state_root"`          // CID of the parent state root at this epoch.
	Event     string `gorm:"column:event;type:miner_sector_event_type;primaryKey" json:"event"` // Name of the event that occurred.
	Height    int64  `gorm:"column:height;type:bigint;primaryKey" json:"height"`                // Epoch at which this event occurred.
}

// TableName MinerSectorEvent's table name
func (*MinerSectorEvent) TableName() string {
	return TableNameMinerSectorEvent
}
