// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMinerPreCommitInfosV9 = "miner_pre_commit_infos_v9"

// MinerPreCommitInfosV9 mapped from table <miner_pre_commit_infos_v9>
type MinerPreCommitInfosV9 struct {
	Height           int64   `gorm:"column:height;type:bigint;primaryKey" json:"height"`
	StateRoot        string  `gorm:"column:state_root;type:text;primaryKey" json:"state_root"`
	MinerID          string  `gorm:"column:miner_id;type:text;primaryKey" json:"miner_id"`
	SectorID         int64   `gorm:"column:sector_id;type:bigint;primaryKey" json:"sector_id"`
	PreCommitDeposit float64 `gorm:"column:pre_commit_deposit;type:numeric;not null" json:"pre_commit_deposit"`
	PreCommitEpoch   int64   `gorm:"column:pre_commit_epoch;type:bigint;not null" json:"pre_commit_epoch"`
	SealedCid        string  `gorm:"column:sealed_cid;type:text;not null" json:"sealed_cid"`
	SealRandEpoch    int64   `gorm:"column:seal_rand_epoch;type:bigint;not null" json:"seal_rand_epoch"`
	ExpirationEpoch  int64   `gorm:"column:expiration_epoch;type:bigint;not null" json:"expiration_epoch"`
	DealIds          *string `gorm:"column:deal_ids;type:bigint[]" json:"deal_ids"`
	UnsealedCid      *string `gorm:"column:unsealed_cid;type:text" json:"unsealed_cid"`
}

// TableName MinerPreCommitInfosV9's table name
func (*MinerPreCommitInfosV9) TableName() string {
	return TableNameMinerPreCommitInfosV9
}
