// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMinerFeeDebt = "miner_fee_debts"

// MinerFeeDebt mapped from table <miner_fee_debts>
type MinerFeeDebt struct {
	Height    int64   `gorm:"column:height;type:bigint;primaryKey" json:"height"`       // Epoch at which this debt applies.
	MinerID   string  `gorm:"column:miner_id;type:text;primaryKey" json:"miner_id"`     // Address of the miner that owes fees.
	StateRoot string  `gorm:"column:state_root;type:text;primaryKey" json:"state_root"` // CID of the parent state root at this epoch.
	FeeDebt   float64 `gorm:"column:fee_debt;type:numeric;not null" json:"fee_debt"`    // Absolute value of debt this miner owes from unpaid fees in attoFIL.
}

// TableName MinerFeeDebt's table name
func (*MinerFeeDebt) TableName() string {
	return TableNameMinerFeeDebt
}
