// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMultisigApproval = "multisig_approvals"

// MultisigApproval mapped from table <multisig_approvals>
type MultisigApproval struct {
	Height         int64   `gorm:"column:height;type:bigint;primaryKey" json:"height"`
	StateRoot      string  `gorm:"column:state_root;type:text;primaryKey" json:"state_root"`
	MultisigID     string  `gorm:"column:multisig_id;type:text;primaryKey" json:"multisig_id"`
	Message        string  `gorm:"column:message;type:text;primaryKey" json:"message"`
	Method         int64   `gorm:"column:method;type:bigint;not null" json:"method"`
	Approver       string  `gorm:"column:approver;type:text;primaryKey" json:"approver"`
	Threshold      int64   `gorm:"column:threshold;type:bigint;not null" json:"threshold"`
	InitialBalance float64 `gorm:"column:initial_balance;type:numeric;not null" json:"initial_balance"`
	GasUsed        int64   `gorm:"column:gas_used;type:bigint;not null" json:"gas_used"`
	TransactionID  int64   `gorm:"column:transaction_id;type:bigint;not null" json:"transaction_id"`
	To             string  `gorm:"column:to;type:text;not null" json:"to"`
	Value          float64 `gorm:"column:value;type:numeric;not null" json:"value"`
	Signers        string  `gorm:"column:signers;type:jsonb;not null" json:"signers"`
}

// TableName MultisigApproval's table name
func (*MultisigApproval) TableName() string {
	return TableNameMultisigApproval
}
