// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameParsedMessage = "parsed_messages"

// ParsedMessage mapped from table <parsed_messages>
type ParsedMessage struct {
	Cid    string  `gorm:"column:cid;type:text;primaryKey" json:"cid"`         // CID of the message.
	Height int64   `gorm:"column:height;type:bigint;primaryKey" json:"height"` // Epoch this message was executed at.
	From   string  `gorm:"column:from;type:text;not null" json:"from"`         // Address of the actor that sent the message.
	To     string  `gorm:"column:to;type:text;not null" json:"to"`             // Address of the actor that received the message.
	Value  float64 `gorm:"column:value;type:numeric;not null" json:"value"`    // Amount of FIL (in attoFIL) transferred by this message.
	Method string  `gorm:"column:method;type:text;not null" json:"method"`     // The name of the method that was invoked on the recipient actor.
	Params *string `gorm:"column:params;type:jsonb" json:"params"`             // Method parameters parsed and serialized as a JSON object.
}

// TableName ParsedMessage's table name
func (*ParsedMessage) TableName() string {
	return TableNameParsedMessage
}
