// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePowerActorClaim = "power_actor_claims"

// PowerActorClaim mapped from table <power_actor_claims>
type PowerActorClaim struct {
	Height          int64   `gorm:"column:height;type:bigint;primaryKey" json:"height"`                      // Epoch this claim was made.
	MinerID         string  `gorm:"column:miner_id;type:text;primaryKey" json:"miner_id"`                    // Address of miner making the claim.
	StateRoot       string  `gorm:"column:state_root;type:text;primaryKey" json:"state_root"`                // CID of the parent state root at this epoch.
	RawBytePower    float64 `gorm:"column:raw_byte_power;type:numeric;not null" json:"raw_byte_power"`       // Sum of raw byte storage power for a miner's sectors. Raw byte power is the size of a sector in bytes.
	QualityAdjPower float64 `gorm:"column:quality_adj_power;type:numeric;not null" json:"quality_adj_power"` // Sum of quality adjusted storage power for a miner's sectors. Quality adjusted power is a weighted average of the quality of its space and it is based on the size, duration and quality of its deals.
}

// TableName PowerActorClaim's table name
func (*PowerActorClaim) TableName() string {
	return TableNamePowerActorClaim
}
