// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReceiptReturn = "receipt_returns"

// ReceiptReturn mapped from table <receipt_returns>
type ReceiptReturn struct {
	Message string   `gorm:"column:message;type:text;primaryKey" json:"message"` // The CID of the message that produced in this receipt.
	Return  *[]uint8 `gorm:"column:return;type:bytea" json:"return"`             // The return of the receipt as bytes.
}

// TableName ReceiptReturn's table name
func (*ReceiptReturn) TableName() string {
	return TableNameReceiptReturn
}
