// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReceipt = "receipts"

// Receipt mapped from table <receipts>
type Receipt struct {
	Message   string `gorm:"column:message;type:text;primaryKey" json:"message"`       // CID of the message this receipt belongs to.
	StateRoot string `gorm:"column:state_root;type:text;primaryKey" json:"state_root"` // CID of the parent state root that this epoch.
	Idx       int64  `gorm:"column:idx;type:bigint;not null" json:"idx"`               // Index of message indicating execution order.
	ExitCode  int64  `gorm:"column:exit_code;type:bigint;not null" json:"exit_code"`   // The exit code that was returned as a result of executing the message. Exit code 0 indicates success. Codes 0-15 are reserved for use by the runtime. Codes 16-31 are common codes shared by different actors. Codes 32+ are actor specific.
	GasUsed   int64  `gorm:"column:gas_used;type:bigint;not null" json:"gas_used"`     // A measure of the amount of resources (or units of gas) consumed, in order to execute a message.
	Height    int64  `gorm:"column:height;type:bigint;primaryKey" json:"height"`       // Epoch the message was executed and receipt generated.
}

// TableName Receipt's table name
func (*Receipt) TableName() string {
	return TableNameReceipt
}
