// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVerifiedRegistryVerifier = "verified_registry_verifiers"

// VerifiedRegistryVerifier mapped from table <verified_registry_verifiers>
type VerifiedRegistryVerifier struct {
	Height    int64   `gorm:"column:height;type:bigint;primaryKey" json:"height"`                   // Epoch at which this verifiers state changed.
	StateRoot string  `gorm:"column:state_root;type:text;primaryKey" json:"state_root"`             // CID of the parent state root at this epoch.
	Address   string  `gorm:"column:address;type:text;primaryKey" json:"address"`                   // Address of verifier this state change applies to.
	DataCap   float64 `gorm:"column:data_cap;type:numeric;not null" json:"data_cap"`                // DataCap of verifier at this state change.
	Event     string  `gorm:"column:event;type:verified_registry_event_type;not null" json:"event"` // Name of the event that occurred.
}

// TableName VerifiedRegistryVerifier's table name
func (*VerifiedRegistryVerifier) TableName() string {
	return TableNameVerifiedRegistryVerifier
}
