// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVisorProcessingReport = "visor_processing_reports"

// VisorProcessingReport mapped from table <visor_processing_reports>
type VisorProcessingReport struct {
	Height            int64     `gorm:"column:height;type:bigint;primaryKey" json:"height"`
	StateRoot         string    `gorm:"column:state_root;type:text;primaryKey" json:"state_root"`
	Reporter          string    `gorm:"column:reporter;type:text;primaryKey" json:"reporter"`
	Task              string    `gorm:"column:task;type:text;primaryKey" json:"task"`
	StartedAt         time.Time `gorm:"column:started_at;type:timestamp with time zone;primaryKey" json:"started_at"`
	CompletedAt       time.Time `gorm:"column:completed_at;type:timestamp with time zone;not null" json:"completed_at"`
	Status            *string   `gorm:"column:status;type:text" json:"status"`
	StatusInformation *string   `gorm:"column:status_information;type:text" json:"status_information"`
	ErrorsDetected    *string   `gorm:"column:errors_detected;type:jsonb" json:"errors_detected"`
}

// TableName VisorProcessingReport's table name
func (*VisorProcessingReport) TableName() string {
	return TableNameVisorProcessingReport
}
