// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVisorGapReport = "visor_gap_reports"

// VisorGapReport mapped from table <visor_gap_reports>
type VisorGapReport struct {
	Height     int64     `gorm:"column:height;type:bigint;primaryKey" json:"height"`
	Task       string    `gorm:"column:task;type:text;primaryKey" json:"task"`
	Status     string    `gorm:"column:status;type:text;primaryKey" json:"status"`
	Reporter   string    `gorm:"column:reporter;type:text;not null" json:"reporter"`
	ReportedAt time.Time `gorm:"column:reported_at;type:timestamp with time zone;not null" json:"reported_at"`
}

// TableName VisorGapReport's table name
func (*VisorGapReport) TableName() string {
	return TableNameVisorGapReport
}
