// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVisorVersion = "visor_version"

// VisorVersion mapped from table <visor_version>
type VisorVersion struct {
	Major int32 `gorm:"column:major;type:integer;primaryKey" json:"major"`
}

// TableName VisorVersion's table name
func (*VisorVersion) TableName() string {
	return TableNameVisorVersion
}
