// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVMMessage = "vm_messages"

// VMMessage mapped from table <vm_messages>
type VMMessage struct {
	Height    int64   `gorm:"column:height;type:bigint;primaryKey" json:"height"`       // Height message was executed at.
	StateRoot string  `gorm:"column:state_root;type:text;primaryKey" json:"state_root"` // CID of the parent state root at which this message was executed.
	Cid       string  `gorm:"column:cid;type:text;primaryKey" json:"cid"`               // CID of the message (note this CID does not appear on chain).
	Source    string  `gorm:"column:source;type:text;primaryKey" json:"source"`         // CID of the on-chain message or implicit (internal) message that caused this message to be sent.
	From      string  `gorm:"column:from;type:text;not null" json:"from"`               // Address of the actor that sent the message.
	To        string  `gorm:"column:to;type:text;not null" json:"to"`                   // Address of the actor that received the message.
	Value     float64 `gorm:"column:value;type:numeric;not null" json:"value"`          // Amount of FIL (in attoFIL) transferred by this message.
	Method    int64   `gorm:"column:method;type:bigint;not null" json:"method"`         // The method number invoked on the recipient actor. Only unique to the actor the method is being invoked on. A method number of 0 is a plain token transfer - no method execution
	ActorCode string  `gorm:"column:actor_code;type:text;not null" json:"actor_code"`   // The CID of the actor that received the message.
	ExitCode  int64   `gorm:"column:exit_code;type:bigint;not null" json:"exit_code"`   // The exit code that was returned as a result of executing the message.
	GasUsed   int64   `gorm:"column:gas_used;type:bigint;not null" json:"gas_used"`     // A measure of the amount of resources (or units of gas) consumed, in order to execute a message.
	Params    *string `gorm:"column:params;type:jsonb" json:"params"`                   // Message parameters parsed and serialized as a JSON object.
	Returns   *string `gorm:"column:returns;type:jsonb" json:"returns"`                 // Result returned from executing a message parsed and serialized as a JSON object.
	Index     int64   `gorm:"column:index;type:bigint;not null" json:"index"`           // Order in which the message was applied.
}

// TableName VMMessage's table name
func (*VMMessage) TableName() string {
	return TableNameVMMessage
}
